### ISSUE TITLE
Missing Binary Package for dev-php/pecl-apcu-5.1.8 with php7 Target

### ISSUE THREAD

**Issue by Lupusalix** [mwitschel/pitoo-overlay#7]
!!! The following binary packages have been ignored due to non matching USE:

    =dev-php/pecl-apcu-5.1.8 php_targets_php5-6
    =dev-php/pecl-apcu-4.0.11 php_targets_php5-6

**Comment by mwitschel** [comment]
has since been resolved

**Comment by mwitschel** [comment]
Has since been resolved...
